# -*- coding: utf-8 -*-
"""TryMakeIR_Quran_ENasStreamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwIaEDMPxIVVGKe3YRDhNA_on7v6nrkI
"""

import streamlit as st
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

st.set_page_config(page_title="Quran Search Engine", page_icon="📖", layout="wide")

st.title("Quran Search Engine")
st.write("Find ayat based on text similiarity. Currently powered by TF-IDF and cosine similarity.")

@st.cache_data
def load_data_and_model():
  # data load
  raw_translation = "https://tanzil.net/trans/en.yusufali"
  df = pd.read_csv(raw_translation, sep="|", names=['surah', 'ayat', 'translation'], comment='#')

  # data cleaning
  df['translation'] = df['translation'].astype(str)
  df['surah'] = df['surah'].astype(int)
  df['ayat'] = df['ayat'].astype(int)

  #vectorization
  tfidf_vectorizer = TfidfVectorizer(stop_words='english')
  tfidf_matrix = tfidf_vectorizer.fit_transform(df['translation'])

  return df, tfidf_vectorizer, tfidf_matrix

# calling function
df, vectorizer, tfidf_matrix = load_data_and_model()

# UI conf

query = st.text_input("Enter the keyword: ")
top_n = st.number_input("Result maximum limit: ", min_value=1, value=10, step=1)

if query:
  query_vec = vectorizer.transform([query])
  sim_scores = cosine_similarity(query_vec, tfidf_matrix).flatten()
  top_indices = sim_scores.argsort()[-top_n:][::-1]

  found = []
  for i in top_indices:
    score = sim_scores[i]
    if score > 0:
      quran_link = f"https://quran.com/{df.iloc[i]['surah']}/{df.iloc[i]['ayat']}"

      found.append({
          'Surah': df.iloc[i]['surah'],
          'Ayat': df.iloc[i]['ayat'],
          'Score': round(score, 4),
          'Translation': df.iloc[i]['translation'],
          'Link': quran_link
      })

  # show result logic
  if found:
    df_found = pd.DataFrame(found)
    st.write(f"Showing top result for: **'{query}'**")

    st.dataframe(
        df_found,
        column_config={
            "Link": st.column_config.LinkColumn("Quran Link")
        },
        hide_index=True,
        use_container_width=True
        )
  else:
    st.warning("The matches ayat with the keyword wasn't found!\nTry another or more universal keyword")